### ISSUE TITLE
Export all book's highlights to directory

### ISSUE THREAD

**Issue by jgornick** [Galarius/pinotate#1]
It would be nice if instead of extracting individual titles that with a directory specified, it would export `{book-title}.md` files to that directory.

**Comment by Galarius** [comment]
@jgornick, I have updated code to export all book's highlights with a single command `python3 pinotate.py`. You can also specify a directory where markdown files with highlights will be saved, just add `-o` flag like this: `python3 pinotate.py -o dir_for_highlights`. 

[Version 0.1](https://github.com/Galarius/pinotate/releases/tag/0.1)
